name: events-service

volumes:
  db_data:

services:
  db:
    image: postgres:15.3-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events_service_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.6
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis-db:/data
